force-app/main/default/objects/Prescription__c/Prescription__c.object-meta.xml
<CustomObject>
    <label>Prescription</label>
    <nameField>
        <label>Prescription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prescription</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prescription__c/fields/Clinical_Encounter__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Encounter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Encounter</label>
    <referenceTo>ClinicalEncounter</referenceTo>
    <relationshipLabel>Prescription</relationshipLabel>
    <relationshipName>Prescription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Dosage__c.field-meta.xml
<CustomField>
    <fullName>Dosage__c</fullName>
    <description>500mg</description>
    <label>Dosage</label>
    <length>23</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>5 Days</description>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <description>Frequency</description>
    <label>Frequency</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Medication_Name__c.field-meta.xml
<CustomField>
    <fullName>Medication_Name__c</fullName>
    <label>Medication Name</label>
    <length>23</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/currentRxViewerController.cls
public with sharing class currentRxViewerController {
    @AuraEnabled
    public static List<Prescription__c> fetchPrescriptionsUnderEncounter(Id encounterId){
        try {
            List<Prescription__c> prescriptions = [
                SELECT Id, Name, Medication_Name__c, Frequency__c, Dosage__c, Duration__c 
                FROM Prescription__c
                WHERE Clinical_Encounter__c = :encounterId
                ORDER BY CreatedDate DESC
            ];

            if(prescriptions.isEmpty()) {
                 return new List<Prescription__c> ();
            } else {
                return prescriptions;
            }

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}