force-app/main/default/objects/ClinicalEncounter/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Attending doctor</description>
    <label>Doctor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Clinical_Encounters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClinicalEncounter/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <description>Notes from visit</description>
    <label>Summary</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Prescription__c/Prescription__c.object-meta.xml
<CustomObject>
    <label>Prescription</label>
    <nameField>
        <label>Prescription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prescription</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Prescription__c/fields/Clinical_Encounter__c.field-meta.xml
<CustomField>
    <fullName>Clinical_Encounter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Clinical Encounter</label>
    <referenceTo>ClinicalEncounter</referenceTo>
    <relationshipLabel>Prescription</relationshipLabel>
    <relationshipName>Prescription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Dosage__c.field-meta.xml
<CustomField>
    <fullName>Dosage__c</fullName>
    <description>500mg</description>
    <label>Dosage</label>
    <length>23</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <description>5 Days</description>
    <label>Duration</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <description>Frequency</description>
    <label>Frequency</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Medication_Name__c.field-meta.xml
<CustomField>
    <fullName>Medication_Name__c</fullName>
    <label>Medication Name</label>
    <length>23</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Prescription__c/fields/Prescribed_By__c.field-meta.xml
<CustomField>
    <fullName>Prescribed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Doctor</description>
    <label>Prescribed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Prescription</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/patientHistoricEncounterViewerController.cls
public with sharing class patientHistoricEncounterViewerController {
    
    @AuraEnabled(cacheable=true)
    public static PatientEncounterWrapper fetchPatientRelatedEncounters(Id selectedEncounterId) {
        try{
            ClinicalEncounter selectedEncounter = [
                SELECT Id, PatientId, Patient.Name
                FROM ClinicalEncounter
                WHERE Id = :selectedEncounterId
                LIMIT 1
            ];

            if (selectedEncounter == null || selectedEncounter.PatientId == null) {
                return null;
            }

            Id patientId = selectedEncounter.PatientId;
            String patientName = selectedEncounter.Patient.Name;

            List<ClinicalEncounter> encounters = [
                SELECT Name, Status , Doctor__r.Name , Summary__c , Category , StartDate,
                    (SELECT Medication_Name__c , Dosage__c , Duration__c , Frequency__c
                    FROM Prescription__r)
                FROM ClinicalEncounter
                WHERE PatientId = :patientId
                ORDER BY StartDate DESC
            ];

            return new PatientEncounterWrapper(patientId, patientName, encounters);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    public class PatientEncounterWrapper {
        @AuraEnabled public Id patientId;
        @AuraEnabled public String patientName;
        @AuraEnabled public List<ClinicalEncounter> encounters;

        public PatientEncounterWrapper(Id patientId, String patientName, List<ClinicalEncounter> encounters) {
            this.patientId = patientId;
            this.patientName = patientName;
            this.encounters = encounters;
        }
    }
}