force-app/main/default/objects/Pharmacy_Requisition__c/Pharmacy_Requisition__c.object-meta.xml
<CustomObject>
    <label>Pharmacy Requisition</label>
    <nameField>
        <label>Pharmacy Requisition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pharmacy Requisition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pharmacy_Requisition__c/fields/Medicine_Name__c.field-meta.xml
<CustomField>
    <fullName>Medicine_Name__c</fullName>
    <label>Medicine Name</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pharmacy_Requisition__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Dispensed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pharmacy_Requisition__c/fields/Surgery_Linked__c.field-meta.xml
<CustomField>
    <fullName>Surgery_Linked__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surgery Linked</label>
    <referenceTo>Surgery__c</referenceTo>
    <relationshipLabel>Pharmacy Requisition</relationshipLabel>
    <relationshipName>Pharmacy_Requisition</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/createPharmacyRequisition.cls
public with sharing class createPharmacyRequisition {

    @AuraEnabled
    public static List<Pharmacy_Requisition__c> getPharmacyRecords(String surgeryId) {
        try {
            return [SELECT Id, Name, Medicine_Name__c, Quantity__c, Status__c FROM Pharmacy_Requisition__c WHERE Surgery_Linked__c = :surgeryId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static Pharmacy_Requisition__c createNewPharmacyRequisition(String surgeryId) {
        try {
            if(!String.isBlank(surgeryId)) {
                Pharmacy_Requisition__c pharmacyRecord = new Pharmacy_Requisition__c(
                    Name = 'New Requisition',
                    Surgery_Linked__c = surgeryId,
                    Status__c = 'Requested'
                );
                insert pharmacyRecord;
                return pharmacyRecord; // return the new record
            } 
            return null;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

}